services:
  - type: web
    name: dev-auth-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run build && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/status
    regions:
      - oregon